[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
    max = ""
  [[module.mounts]]
    source = 'assets'
    target = 'assets'

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = false

# use the following setings for regular Google Analytics integration
[params.modules.GoogleAnalytics]
  integration = "core" 
  state = "async"
  category = "analytics"
  gcm = false

# use the following setings when using Google Consent Mode v2
# [params.modules.GoogleAnalytics]
#   integration = "critical" # set to critical when using Google Consent Mode v2
#   state = "immediate"
#   category = "necessary"
#   gcm = true

[params.modules.GoogleAnalytics.csp]
  script-src = [
      "*.google-analytics.com",
      "*.googletagmanager.com"
  ]
  connect-src = [
      "*.analytics.google.com",
      "*.google.com",
      "*.google-analytics.com",
      "*.googletagmanager.com"
  ]
  frame-src = [
      "*.googletagmanager.com"
  ]
  img-src = [
      "*.google-analytics.com",
      "*.googletagmanager.com"
  ]
