[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
    max = ""
  [[module.mounts]]
    source = 'assets'
    target = 'assets'

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = false

[params.modules.GoogleAnalytics]
  integration = "core"
  state = "async"
  category = "analytics"

[params.modules.GoogleAnalytics.csp]
  script-src = [
      "*.google-analytics.com",
      "*.googletagmanager.com"
  ]
  connect-src = [
      "*.google-analytics.com",
      "*.analytics.google.com",
      "*.googletagmanager.com"
  ]
  img-src = [
      "*.google-analytics.com",
      "*.googletagmanager.com"
  ]
