baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-google-analytics'

[services]
  [services.googleAnalytics]
    ID = "G-T85PPZ36GN"

[params.debugging]
    showJS = true

[params.modules.GoogleAnalytics]
  force = true

[module]
  # Build and serve using local mod-google-analytics clone declared in the named Hugo workspace:
  workspace = "mod-google-analytics.work"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.imports]]
    path = "github.com/gethinode/mod-google-analytics"
  [[module.imports.mounts]]
    source = "assets/js/modules/google-analytics/google-analytics.js"
    target = "assets/js/google-analytics.js"
  [[module.imports]]
    path = "github.com/gethinode/mod-utils/v2"
